config/routes.rb
Rails.application.routes.draw do
  resources :styles

  resources :memberships

  resources :beer_clubs

  resources :users

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'

  get 'places', to: 'places#index'
  post 'places', to:'places#search'

  delete 'signout', to: 'sessions#destroy'

  resource :session, only: [:new, :create, :delete]

  resources :beers

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  resources :users do
    post 'toggle_ban', on: :member
  end

  resources :styles

  resources :places, only:[:index, :show]

  post 'places', to:'places#search'

  resources :ratings, only: [:index, :new, :create, :destroy]

  get 'beerlist', to:'beers#list'

  root 'breweries#index'

  get 'ngbeerlist', to:'beers#nglist'

  get 'brewerylist', to: 'breweries#list'

end

app/models/user.rb
class User < ActiveRecord::Base
  include RatingAverage

  has_secure_password

  has_many :ratings, dependent: :destroy
  has_many :beers, through: :ratings
  has_many :memberships, dependent: :destroy
  has_many :beer_clubs, through: :memberships

  validates :username, uniqueness: true,
            length: { in: 3..15 }

  validates :password, length: { minimum: 4 }

  validates :password, format: { with: /\d.*[A-Z]|[A-Z].*\d/,  message: "has to contain one number and one upper case letter" }

  def favorite_beer
    return nil if ratings.empty?
    ratings.order(score: :desc).limit(1).first.beer
  end

  def favorite_brewery
    return nil if ratings.empty?
    brewery_ratings = rated_breweries.inject([]) { |set, brewery| set << [brewery, brewery_average(brewery) ] }
    brewery_ratings.sort_by{ |r| r.last }.last.first
  end

  def favorite_style
    return nil if ratings.empty?
    style_ratings = rated_styles.inject([]) { |set, style| set << [style, style_average(style) ] }
    style_ratings.sort_by{ |r| r.last }.last.first
  end

  #private

  def rated_styles
    ratings.map{ |r| r.beer.style }.uniq
  end

  def style_average(style)
    ratings_of_style = ratings.select{ |r| r.beer.style==style }
    ratings_of_style.inject(0.0){ |sum, r| sum+r.score}/ratings_of_style.count
  end

  def rated_breweries
    ratings.map{ |r| r.beer.brewery}.uniq
  end

  def brewery_average(brewery)
    ratings_of_brewery = ratings.select{ |r| r.beer.brewery==brewery }
    ratings_of_brewery.inject(0.0){ |sum, r| sum+r.score}/ratings_of_brewery.count
  end

  def self.top(n)
    most_ratings = User.all.sort_by{ |b| -(b.ratings.count) }
    most_ratings.take(n)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.includes(:ratings, :beers).all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if user_params[:username].nil? and @user == current_user and @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if current_user == @user
      @user.destroy
      session[:user_id] = nil
    end
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def toggle_ban
    user = User.find(params[:id])
    user.update_attribute :banned, (not user.banned)

    new_status = user.banned? ? "banned" : "active"

    redirect_to :back, notice:"User status changed to to #{new_status}"
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @user.new_record? %>
    <div class="field">
      <%= f.label :username %><br />
      <%= f.text_field :username %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Change password of <%= @user.username %></h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table class="table table-hover">
  <thead>
  <tr>
    <th>Username</th>
    <th> rated beers </th>
    <th> total ratings </th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
        <td><%= user.beers.size %></td>
        <td><%= user.ratings.size %></td>
        <td><% if user.banned  %>
              <span class="label label-info">Frozen</span>
          <%end%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <%= @user.username %>
  <% if @user.banned  %>
      <span class="label label-info">Frozen</span>
      <%end%>
</h2>

<% if @user.ratings.empty? %>
    <p>has not yet rated any beers</p>
<% else %>
    <p>
      Has made <%= pluralize(@user.ratings.count, 'rating') %>, average <%= @user.average_rating %>
    </p>
<% end %>

<% if @user.beer_clubs.any? %>
    member of
    <% @user.beer_clubs.each do |club| %>
        <%= link_to club.name, club %>
    <% end %>
<% end %>

<ul>
  <% @user.ratings.each do |rating| %>
      <li>
        <%= rating %>
        <% if @user == current_user %>
            <%= link_to 'delete', rating, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </li>
  <% end %>
</ul>
<p>

  <% status = "Reactivate" %>
  <% status= "Freeze" unless @user.banned%>

  <%=link_to "#{status} account", toggle_ban_user_path(@user.id), method: :post, class: "btn btn-warning" if current_user.admin and current_user.id != @user.id%>

</p>

<% if @user == current_user %>
    <%= link_to 'Change password', edit_user_path(@user) %>
    <%= link_to 'Delete account', @user, method: :delete, data: { confirm: 'Are you sure?' } %></
<% end %>